


[Internal="JPH::BodyCreationSettings"]
object BodyCreationSettings {
	BodyCreationSettings new();
};

[Internal="hjolt::Config"]
object Config {
	Config new();
	attribute int maxTempAllocatorSize;
	attribute int maxPhysicsJobs;
	attribute int maxPhysicsBarriers;
	attribute int maxThreads;
	attribute int maxBodies;
	attribute int numBodyMutexes;
	attribute int maxBodyPairs;
	attribute int maxContactConstraints;
};

[Internal="hjolt::Globals"]
object Globals {
	Globals new( Config config );

};
