


[Internal="JPH::BodyCreationSettings"]
object BodyCreationSettings {
	BodyCreationSettings new();
};

[Internal="hjolt::Config"]
object JoltConfig {
	JoltConfig new();
	attribute int maxTempAllocatorSize;
	attribute int maxPhysicsJobs;
	attribute int maxPhysicsBarriers;
	attribute int maxThreads;
	attribute int maxBodies;
	attribute int numBodyMutexes;
	attribute int maxBodyPairs;
	attribute int maxContactConstraints;
};

[Internal="hjolt::PhysicsSystemWrapper"]
object JoltSystem {


};

[Internal="hjolt::Globals"]
object JoltGlobals {
	JoltGlobals new( JoltConfig *config );
	JoltSystem *createSystem();
	void updateSystem(JoltSystem *system, float deltaTime, int collisionSubSteps);

};
